### ISSUE TITLE
JSDoc comments for typescript stopped working upgrading from 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by Gambero81** [mobermeyer/DocStubsJs#11] opened 2015-10-31 22:43 UTC
Upgrading DocStubsJs extension from version 2.1.2 to version 2.1.3 cause JSDoc comment stopped working for TypeScript.
If i type /*\* nothing happens, jsdoc comment block is not generated..

**Comment by mobermeyer** [comment] 2015-10-31 23:04
Thanks Gambero. I do not seem to be having any issues. Can you tell me which version of Visual Studio you are using, and if possible, the function you are trying to comment?

**Comment by Gambero81** [comment] 2015-11-01 20:25
i have debugged the issue and i'm going to explain 2 bugs i found:

first:

<img width="960" alt="immagine1" src="https://cloud.githubusercontent.com/assets/13186600/10871116/7441d682-80de-11e5-99e8-974075c6a415.png">

put the open bracket of run method on new line then start comment block /**

<img width="960" alt="immagine2" src="https://cloud.githubusercontent.com/assets/13186600/10871120/a31b6ee6-80de-11e5-915c-ce02fa04cf4b.png">

in GetTypeScriptFunctionLine method i put a breakpoint on capture.GetText where you can see the problem: lineEnd.End.Position - startTextAfterParams result -1 causing the exception

<img width="960" alt="immagine3" src="https://cloud.githubusercontent.com/assets/13186600/10871140/15071e06-80df-11e5-8eec-ea3a78d26622.png">

**Comment by Gambero81** [comment] 2015-11-01 20:31
second:

<img width="960" alt="immagine4" src="https://cloud.githubusercontent.com/assets/13186600/10871152/515795f2-80df-11e5-8b8d-f83f84185d00.png">

change speak method as above and start comment block /**

<img width="960" alt="immagine5" src="https://cloud.githubusercontent.com/assets/13186600/10871162/82511872-80df-11e5-957c-40c0037a7e44.png">

as you can see method GetTypeScriptFunctionLine return -1 because textAfterParams variable do not starts with ":"

<img width="960" alt="immagine6" src="https://cloud.githubusercontent.com/assets/13186600/10871175/be94628a-80df-11e5-8595-072a4235e8d3.png">

this cause capture.GetLineFromNumber method to throw an exception

<img width="960" alt="immagine7" src="https://cloud.githubusercontent.com/assets/13186600/10871180/dd47082c-80df-11e5-9067-e11b61caa7a0.png">

**Comment by Gambero81** [comment] 2015-11-01 20:34
NB: I'm using visual studio 2015 Enterprise with WebEssentials extension, in WebEssentials extension settings i have put Auto-complete multi-line comments to False.

Thanks

**Comment by Gambero81** [comment] 2015-11-01 20:54
i found a third bug, this time using VSDoc comment style:

<img width="960" alt="immagine8" src="https://cloud.githubusercontent.com/assets/13186600/10871273/92ae8c4c-80e2-11e5-9099-9569a195baef.png">

start /// comment block cause GetTypeScriptFunctionLine return -1, note lineText variable value !!

<img width="960" alt="immagine9" src="https://cloud.githubusercontent.com/assets/13186600/10871277/bf8d27c8-80e2-11e5-9003-0b15357eb0cd.png">

having lineNum = -1 cause exception on capture.GetLineFromLineNumber method

<img width="960" alt="immagine10" src="https://cloud.githubusercontent.com/assets/13186600/10871288/141df970-80e3-11e5-80e4-553beb48a981.png">

**Comment by mobermeyer** [comment] 2015-11-01 21:06
Thank you very much Gambero for the details. The first two bugs I was able to fix (they were both caused by 1 too many +1's)

The third issue isn't exactly a bug, but it definitely exposes a portion of the code I am definitely not proud of. VSDoc comments, by specification, are not meant to go above function signatures, but inside the function body, itself. https://msdn.microsoft.com/en-us/library/bb514138.aspx

Currently, I "solved" this by letting it throw an exception when it looks for the function declaration line number. It is definitely something I want to fix some day, but right now it is behaving as intended. I may also provide an option to allow vsdoc comments to be placed above the function, but that should be considered a separate issue. For now, since I fixed the first two bugs, I will close this issue. Thanks again for bringing it to my attention and providing me the details that made it easier to fix.

**Closed as completed by mobermeyer** 2015-11-01 21:06 UTC
